
const { Item } = require('../models');

module.exports = {
  up: (queryInterface) => queryInterface.bulkInsert(Item.tblName, [
    {
      item_id: 1,
      item_name: 'Large Egg',
      category: 'Egg',
      size: 'large',
      price: 900,
      unit: 'Crate',
      image: 'uploads/egg.jpg',
      description: 'Large sized egg',
      quantity: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 2,
      item_name: 'Medium Egg',
      category: 'Egg',
      price: 820,
      size: 'medium',
      unit: 'Crate',
      quantity: 1,
      image: 'uploads/egg.jpg',
      description: 'Medium sized egg',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 3,
      item_name: 'Small Egg',
      category: 'Egg',
      price: 670,
      size: 'small',
      unit: 'Crate',
      quantity: 1,
      image: 'uploads/egg.jpg',
      description: 'Pullet sized egg',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 4,
      item_name: 'Cracked Egg',
      category: 'Egg',
      price: 570,
      size: 'ungraded',
      quantity: 1,
      image: 'uploads/damaged.jpg',
      unit: 'Crate',
      description: 'Unsorted craked/damaged eggs',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 5,
      item_name: 'Ungraded Egg',
      category: 'Egg',
      size: 'ungraded',
      quantity: 1,
      image: 'uploads/ungraded.jpg',
      price: 750,
      unit: 'Crate',
      description: 'All sizes. i.e unsorted eggs',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 6,
      item_name: 'Small Cockerel',
      category: 'Cockerel',
      price: 900,
      size: '1-2kg',
      unit: 'Bird',
      quantity: 1,
      image: 'uploads/upload_9ec552bd6a22ed9587aaa305ea58149a.jpeg',
      description: 'Small sized Cockerel',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 7,
      item_name: 'Medium Cockerel',
      category: 'Cockerel',
      price: 1200,
      size: '2-3kg',
      unit: 'Bird',
      quantity: 1,
      image: 'uploads/upload_9ec552bd6a22ed9587aaa305ea58149a.png',
      description: 'Medium sized Cockerel',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 8,
      item_name: 'Large Cockerel',
      category: 'Cockerel',
      size: '3-4kg',
      price: 2000,
      unit: 'Bird',
      quantity: 1,
      image: 'uploads/upload_9c503c94170a73b08f8273e2ac2f5335.jpg',
      description: 'Large sized Cockerel',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 9,
      item_name: 'Manure',
      category: 'Manure',
      price: 500,
      size: '100kg',
      unit: 'Bag',
      quantity: 1,
      image: 'uploads/manure.jpg',
      description: 'Chicken litters.',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 10,
      item_name: 'Old layer',
      category: 'Old layer',
      price: 1400,
      size: 'All sizes',
      unit: 'Bird',
      quantity: 0,
      image: 'uploads/spent_layer.jpg',
      description: 'Spent layers.',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 11,
      item_name: 'Layer Mash (Hybrid)',
      category: 'feed',
      price: 3300,
      brand: 'Hybrid',
      size: '25',
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      unit: 'kg',
      quantity: 0,
      description: 'Hybrid layer mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 12,
      item_name: 'Grower Mash (Hybrid)',
      category: 'feed',
      price: 3300,
      brand: 'Hybrid',
      size: '25',
      unit: 'kg',
      quantity: 0,
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      description: 'Hybrid grower mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 13,
      item_name: 'Chick Mash (Hybrid)',
      category: 'feed',
      price: 3300,
      brand: 'Hybrid',
      size: '25',
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      unit: 'kg',
      quantity: 0,
      description: 'Hybrid chick mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 14,
      item_name: 'Layer concentrate (Hybrid)',
      category: 'concentrate',
      price: 3300,
      brand: 'Hybrid',
      size: '25',
      image: 'uploads/upload_064bd6a1f2a4a468c8a163469cac9424.png',
      unit: 'kg',
      quantity: 0,
      description: '30% Hybrid layer concentrate (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 15,
      item_name: 'Layer Mash (Vita)',
      category: 'feed',
      price: 3400,
      brand: 'Vita',
      image: 'uploads/vita-layer-mash.png',
      size: '25',
      unit: 'kg',
      quantity: 0,
      description: 'Vita layer mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 16,
      item_name: 'Grower Mash (Vita)',
      category: 'feed',
      price: 3300,
      brand: 'Vita',
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      size: '25',
      unit: 'kg',
      quantity: 0,
      description: 'Vita grower mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 17,
      item_name: 'Chick Mash (Vita)',
      category: 'feed',
      price: 4080,
      brand: 'Vita',
      size: '25',
      unit: 'kg',
      quantity: 0,
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      description: 'Vita chick mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 18,
      item_name: 'Layer mash (Formulated)',
      category: 'feed',
      price: 3300,
      brand: 'BhammyFarms',
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      size: '25',
      unit: 'kg',
      quantity: 0,
      description: 'Formulated chick mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 19,
      item_name: 'Grower mash (Formulated)',
      category: 'feed',
      price: 3300,
      brand: 'BhammyFarms',
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      size: '25',
      unit: 'kg',
      quantity: 0,
      description: 'Formulated chick mash (25kg).',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      item_id: 20,
      item_name: 'Lasota',
      category: 'vaccine',
      image: 'uploads/upload_4fe6d673f25db8749ce6e119d2d899d6.jpg',
      price: 2000,
      brand: 'Biovac',
      size: '1000',
      unit: 'dose',
      quantity: 0,
      description: 'Biovac Lasota.',
      created_at: new Date(),
      updated_at: new Date()
    }
  ]),

  down: (queryInterface) => queryInterface.bulkDelete(Item.tblName, null, {})
};
