const ROUTES = {
  ACTIVITIES: 'Activities',
  BATCHES: 'Batches',
  BATCH_DETAIL: 'BatchDetail',
  CUSTOMERS: 'Customers',
  CUSTOMER_DETAIL: 'CustomersDetail',
  DASHBOARD: 'Dashboard',
  EDIT_EMPLOYEE: 'EditEmployee',
  EMPLOYEE: 'Employee',
  EMPLOYEES: 'Employees',
  EXPENSES: 'Expenses',
  FEEDS: 'Feeds',
  INCOME: 'Income',
  INCOME_DETAIL: 'IncomeDetail',
  NEW_INCOME: 'NewIncome',
  EDIT_INCOME: 'EditIncome',
  NEW_PRODUCTION: 'NewProduction',
  PRODUCTION: 'Production',
  PRODUCTIONS: 'Productions',
  REPORT: 'Report',
  REPORTS: 'Reports',
  SETTINGS: 'Settings',
  STORE: 'Store',
  SCHEDULES: 'Schedules',
  VIEW_EMPLOYEE: 'ViewEmployee',
};

export default ROUTES;
